# Generated by Django 4.1.7 on 2025-03-11 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_registration_user_status2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='user_status2',
        ),
    ]
